# Generated by Django 5.0.6 on 2024-07-23 06:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=128)),
                ('dob', models.DateField(max_length=8)),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=12)),
                ('Email', models.EmailField(blank=True, max_length=70)),
                ('Category', models.CharField(choices=[('B', 'Family Tours'), ('R', 'Religious Tours'), ('S', 'Solo Trips'), ('A', 'Adventure Trips')], max_length=128)),
                ('No_of_Days', models.IntegerField()),
                ('No_of_Childrens', models.IntegerField()),
                ('No_of_Adults', models.IntegerField()),
                ('Enquiry_message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name', max_length=100)),
                ('location', models.CharField(help_text='location', max_length=100)),
                ('img', models.ImageField(default='media/image.jpg', upload_to='media/images')),
                ('description', models.CharField(default=0, help_text='description', max_length=250)),
                ('places_to_explore', models.CharField(default=0, help_text='places to explore', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_category', models.CharField(max_length=50)),
                ('subcategory', models.CharField(max_length=200)),
                ('packages', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('information', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.category')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(help_text='Place', max_length=100)),
                ('location', models.CharField(default=0, help_text='Location', max_length=100)),
                ('image', models.ImageField(default='media/image.jpg', upload_to='media/images')),
                ('price', models.IntegerField(default=0)),
                ('places_to_explore', models.CharField(default='', help_text='Places to explore', max_length=250)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('packages', models.ManyToManyField(to='tour.packages')),
                ('places', models.ManyToManyField(to='tour.places')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=150)),
                ('email', models.CharField(default='', max_length=150)),
                ('contact', models.CharField(default='', max_length=15)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.trip')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
            },
        ),
    ]
